### ISSUE TITLE
Slime Repl doesn't start by default

### ISSUE THREAD

**Issue by mrkkrp** [slime/slime#258]
I used so-called `slime-helper` previously (installed via Quicklisp) and it worked. Now I've installed Slime via Emacs' package manager (MELPA).

Previously, when I called `slime`, fancy Repl was displayed, but now `slime` only creates `*inferior-lisp*` buffer. I need to manually call `slime-repl`. Is it normal behavior? I've read this in manual:

> SLIME is started with the Emacs command M-x slime. This uses the inferior-lisp package to start a Lisp process, loads and starts the Lisp-side server (known as “Swank”), and establishes a socket connection between Emacs and Lisp. Finally a REPL buffer is created where you can enter Lisp expressions for evaluation.

So, it seems like Repl should be invoked automatically.

Relevant config portion:

```
(setq inferior-lisp-program "sbcl" ; Steel Bank Common Lisp
      slime-contribs '(slime-fancy))
```

Slime 20150709.613, SBCL 1.2.12, Emacs trunk, Arch Linux.

**Comment by luismbo** [comment]
Can you reproduce with `emacs -q` and minimal slime config?

**Comment by mrkkrp** [comment]
Yes, here is how:

1. Run `emacs -q` or `emacs -Q`:

2. Evaluate the following:
    ```
    (package-initialize)
    (require 'slime)
    
    (setq inferior-lisp-program "sbcl" ; Steel Bank Common Lisp
          slime-contribs '(slime-fancy))
    ```

3. Call Slime via <kbd>M-x slime</kbd>.

**Comment by mrkkrp** [comment]
Any idea why this might happen?

**Comment by luismbo** [comment]
I'm not sure. Can you grab slime from git and do a git bisect?

**Comment by luismbo** [comment]
Oh, sorry. I know what's wrong. You need to customise SLIME first, and require it afterwards. Or use `(require 'slime-autoloads)` instead of `(require 'slime)`.

**Comment by mrkkrp** [comment]
I'm trying to make it work (requiring `slime-autoloads` instead of `slime`), but with no luck. Can you please put here minimal config that works for you?

**Comment by luismbo** [comment]
This works for me:

```
(package-initialize)
(require 'slime-autoloads)

(setq inferior-lisp-program "sbcl" ; Steel Bank Common Lisp
      slime-contribs '(slime-fancy))
```

**Comment by mrkkrp** [comment]
Great, I managed to make it work now. Is it how it's supposed to function? Can you make a change so user can require `slime`? If you prefer to keep this current behavior, please mention it somewhere, so people know that they need to require `slime-autoloads` instead.

**Comment by luismbo** [comment]
Actually, when using MELPA, the package systems takes care of setting up the autoloads for you, so you don't even have to require those.

The installation instructions mention all of this: https://common-lisp.net/project/slime/doc/html/Installation.html#Installing-from-Git Perhaps you'd like to suggest improvements to the wording?

**Comment by luismbo** [comment]
Making `M-x slime` take into account contribs that are specified after `(require 'slime)` would be nice. I'll reopen this issue to look into that but I won't have time myself to investigate how to do that in the coming days. Perhaps you feel like digging in? :-)

**Comment by mrkkrp** [comment]
Great. I require `slime` simply because I wanted to get rid of "undefined variable" warnings in my init file from flycheck. The only thing I don't currently like that such an obvious thing as requiring `slime` breaks it. When you require a package, do you expect it to cease to function because of this?

**Comment by mrkkrp** [comment]
Oh, I would like to help, actually. I have experience with Emacs Lisp and Common Lisp, but I know nothing about internal workings of Slime. I could take a look at source code, although I cannot promise anything.

**Comment by luismbo** [comment]
@mrkkrp I agree. The current behavior is unintuitive and should be fixed.

**Comment by capitaomorte** [comment]
@mrkkrp and @luismbo 

```
(package-initialize)
(require 'slime)

(setq inferior-lisp-program "sbcl" ; Steel Bank Common Lisp
      slime-contribs '(slime-fancy))
```

For this recipe to work you need to add `(slime-setup)` to the end. Alternatively, replace

```
(setq slime-contribs '(slime-fancy)) 
```

with

```
(slime-setup '(slime-fancy))
```

This was the "classic" recipe for making SLIME consider contribs. It still works, was removed if I remember correctly, once it was replaced with the more idiomatic and simpler version of using `slime-autoloads`. `slime-autoloads` is the only package that will automatically load contribs, something that SLIME has always resisted.

**Comment by mrkkrp** [comment]
`slime.el` has `(slime-setup)` at the end. Does it initialize something without loading of contributions? Can we just remove that line? `slime-autoloads` doesn't do `(slime-setup)` for example. Sorry if I don't understand something.

**Comment by mrkkrp** [comment]
Would it be better to remove `(slime-setup)` from `slime.el` and mention it in the manual, so users just call it in their init files?

**Comment by mrkkrp** [comment]
Ah, I get it. `slime-autoloads.el` declares `slime-contribs`, and autoload for `slime` among other things. Users sets value of `slime-contribs` but `slime.el` is still not loaded, so `slime-setup` is not called until user calls `slime`, then `(slime-setup)` loads contribs specified in `slime-contribs`, since it's not given explicit argument. I would remove `(slime-setup)` from `slime.el` and mention it in manual explicitly. Many Emacs Lisp packages require user to add call to some initializing function in their files, so this would be idiomatic, I think.

**Comment by mrkkrp** [comment]
If user will have to explicitly call `slime-setup`, he will need to require/load slime too early, though. This eliminates benefits of autoloading. So I think @luismbo should just mention `slime-setup` in manual, so users who require Slime, should call `slime-setup`. Sorry, for my verbose output in previous posts :)

**Comment by luismbo** [comment]
The problem with `slime-setup` is that it forces slime to be loaded at startup and that is one of the reasons why @capitaomorte deprecated it in favor of `slime-contribs`. I suppose one solution would be to call `slime-setup` when `slime` is invoked at runtime instead of at load-time. @mrkkrp, do you want to experiment with that and see if it works?

**Comment by mrkkrp** [comment]
@luismbo, It shouldn't be hard, I'll try to find time and see if it's a good idea. If such change is to be made, we should make sure that `slime-setup` is executed only once, though.

**Comment by capitaomorte** [comment]
@mrkkrp, just out of curiosity, why are you interested in this? If I read you correctly

> I required slime simply because I wanted to get rid of "undefined variable" warnings in my init file from flycheck.

But if you require `slime-autoloads` instead it doesn't happen, because `slime-autoloads` does define the variable. You can set `slime-contribs` once and that's it.

If, on the other hand, you are interested in having contribs be loaded with just `M-x slime` by default, with no call to `slime-setup` or setting of `slime-contribs`, then you may face some resistance.

But I may be misreading your intentions...

**Comment by mrkkrp** [comment]
@capitaomorte, Right now I have no problems. `slime-autoloads` is loaded for me by default, I don't need to require it. To tame Flycheck I use this:

```
(eval-when-compile
  (require 'slime)
  (require 'slime-repl))
```

And that's it, Flycheck is happy and all that `slime-autoloads` story plays well. However, I agree that just requiring of `slime` should not result in inability to customize which contribs will be used.

@luismbo asked me if I want to experiment and see if it loading contribs on calling of `slime` works, well, this is something I can do, and that should be pretty easy, so why not.

> If, on the other hand, you are interested in having contribs be loaded with just M-x slime by default, with no call to slime-setup or setting of slime-contribs, then you may face some resistance.

I'm not going to change something radically. That's your work, I think. I only said I could test if it would work for me.

**Comment by capitaomorte** [comment]
> To tame Flycheck I use this:
> (eval-when-compile (require 'slime) (require 'slime-repl))

But why don't you "tame flycheck" by using 

```elisp
(require 'slime-autoloads)
(setq slime-contribs '(slime-repl))
```
It shouldn't give you any errors when compiling a file with such a snippet, as long as `slime-autoloads` is in the load path. It's one less line and more idiomatic anyway. You don't need the `eval-when-compile` since `require` forms are automatically `eval-and-compile` when present at top-level.

> I'm not going to change something radically. That's your work, I think. 

I think you got the impression that I didn't "like" what you were proposing. That's not necessarily true, I just want to understand its motivations, there may be something interesting. I still don't, but don't waste too much time explaining if you don't  want to, just go ahead.

**Comment by mrkkrp** [comment]
@capitaomorte, I use that snippet because I need variables and functions that are missing in `slime-autoloads` in my config and I don't want to see "free/undefined variable" stuff.

**Comment by mrkkrp** [comment]
@capitaomorte, `slime-autoloads` is automatically loaded by package system by the way.

**Comment by capitaomorte** [comment]
> @capitaomorte, I use that snippet because I need variables and functions that are missing in slime-autoloads in my config and I don't want to see "free/undefined variable" stuff.

Ah, ok, that makes sense. What variables exactly, out of curiosity?

**Comment by mrkkrp** [comment]
`inferior-lisp-program` for example. It's more about functions, though. Here is my whole setup, see for yourself: https://github.com/mrkkrp/dot-emacs/blob/master/mk/mk-lisp.el

**Comment by luismbo** [comment]
The point of the experiment I suggested to @mrkkrp is that even though

```(require 'slime-autoloads) 
(setq slime-contribs ...)```

is the documented way to setup slime (and has the advantage of not forcing slime to be loaded at startup), I think

```(require 'slime) 
(setq slime-contribs ...)```

should work as well.

**Comment by luismbo** [comment]
In other words, it's surprising that setting slime-contribs after slime is loaded has no effect.

**Comment by capitaomorte** [comment]
> inferior-lisp-program for example. 

It belongs, not to slime but to `inf-lisp`. Require it to get rid of the warning. Though it could/should probably be declared in `slime-autoloads` as well. 

>It's more about functions, though. Here is my whole setup, see for yourself: https://github.com/mrkkrp/dot-emacs/blob/master/mk/mk-lisp.el

The only thing that might trigger a warning unless `slime.el` is fully loaded is this snippet at
https://github.com/mrkkrp/dot-emacs/blob/master/mk/mk-lisp.el#L62
```elisp
(τ slime     slime-repl "C-c r" #'slime-restart-inferior-lisp)
```
I assume your funny `τ` does some kind of key-binding antics, but you shouldn't be using `#'` in that case to extract a function object that might not exist yet. You should be using just the symbol `slime-restart-inferior-lisp`, which can always be interned. This is the standard way to do keybindings in Emacs before packages defining those bindings are loaded. 

Any other problems that are forcing you to throw away the advantages of autoloads?

> In other words, it's surprising that setting slime-contribs after slime is loaded has no effect.

Granted. The contrib system itself is quite surprising itself.

I can't see any disadvantages of calling `slime-setup` on every `slime` call right now, but I seriously doubt there aren't any. Good luck!

**Comment by luismbo** [comment]
> I can't see any disadvantages of calling slime-setup on every slime call right now, but I seriously doubt there aren't any.

Right, where the idea might crumble is on how to deal with pre-existing slime connections. Perhaps we will need to compromise there somehow. We'll see...

**Comment by mrkkrp** [comment]
> I assume your funny τ does some kind of key-binding antics, but you shouldn't be using #' in that case to extract a function object that might not exist yet. You should be using just the symbol slime-restart-inferior-lisp, which can always be interned. This is the standard way to do keybindings in Emacs before packages defining those bindings are loaded.

It's just:

```emacs-lisp
(defmacro τ (file keymap key fnc)
  "When FILE is loaded, add to KEYMAP key binding KEY (invoking FNC)."
  `(eval-after-load ',file
     '(define-key
        (symbol-value (intern (concat (symbol-name ',keymap) "-mode-map")))
        (kbd ,key) ,fnc)))
```

So, function object always exist by the time this gets evatuated. And `#'` is also a stylistic element, this way I specify that this is a function, not just a symbol.

> Any other problems that are forcing you to throw away the advantages of autoloads?

Not sure why you think so, I do not throw away advantages of autoloads, I use autoloads everywhere and my Emacs starts *really* fast.

**Comment by capitaomorte** [comment]
> So, function object always exist by the time this gets evatuated. 

But not when some usage of it compiled, which is what is causing the error.

> And #' is also a stylistic element, this way I specify that this is a function, not just a symbol.

But, if you use autoloads, that function doesn't exist when you are compiling you init file. What you see as more stylish is seen by others as wasting the indirection that `funcall`ing symbols allows. And keybindings in emacs typically make full use of that indirection. 

Still, if you must keep the `#'`. I personally recommend that you use `eval-after-load`, but that may destroy the benefits of byte-compiling the init file (which, as an aside, frankly really don't seem that big anyway, have you measured?)

> I use autoloads everywhere and my Emacs starts really fast.

It could start even faster if you used autoloads for `slime`.

In your config file I see that you `require`  `slime`, `slime-autoloads` and other slime-related stuff at _compile_ time. I don't see any requiring it at _load_ time. So I'm curious what would happen in a session where you just try to load the `.elc` file. 

Perhaps you're testing in the same session where you have compiled it.

Can you explain how the compiled `elc` file(s) that you are trying to build will load slime? Some kind of `require`ing or is going to have to happen right? Will it do it by `require 'slime` or `require 'slime-autoloads`.

A good way to test the above is start your Emacs from scratch and check if `C-h f slime RET` says that `slime` is an autoloaded function.

**Comment by mrkkrp** [comment]
Oh man, this is really off-topic imho and I know what I'm doing (or at least I think so), so if you took real interest in my configuration (I restarted my Emacs to get this):

```
slime is an interactive autoloaded Lisp function in ‘slime.el’.

It is bound to <menu> l i.

[Arg list not available until function definition is loaded.]

Start a Lisp subprocess and connect to its Swank server.
```

So, this is autoloaded, I do not require `slime` at all, and `slime-autoloads.el` is loaded by `package-initialize` or anyway it's handled by package system. Now, Flycheck uses byte-compilation warnings/error to report stuff, so I add `eval-when-compile` -- this does not affect start up time or something, only removes unnecessary Flycheck warnings. If you want to discuss my config, open an issue there, because I don't think it's really relevant in this thread.

**Comment by mrkkrp** [comment]
> Still, if you must keep the #'. I personally recommend that you use eval-after-load

I really don't understand, this is what "tau" form does exactly, it expands to `eval-after-load`.

**Comment by mrkkrp** [comment]
@capitaomorte, To make it clear: I agreed to test it not because it affects my own config, but just to help this project. I do not require `slime` at load time, I use autoloads. And tau form creates key-bindings after loading of source files, so functions always exist then. I think I made myself clear now.

**Comment by capitaomorte** [comment]
> I really don't understand, this is what "tau" form does exactly, it expands to eval-after-load.

My bad for not reading it correctly! So it doesn't raise any errors there, right?

> slime-autoloads.el is loaded by package-initialize

That explains it thanks. Sorry for not remembering this, you had already mentioned it before.

> If you want to discuss my config,

Obviously not. Let me explain: I'm trying to figure out if (1) if your config is somehow representative of a class of legitimate user configurations and (2) what the problems generated are. If (1) is true and (2) is the non-empty set then probably something should be improved in SLIME.

Otherwise, I see nothing to improve. No need to *ever* require `slime` in your init files and hence no need to call `slime-setup` when it runs.

The only instance of (2) seems now to be a warning about `inferior-lisp-program`. Why don't you drop that in an `eval-after-load` too? 

I told you before and have to tell you again.

> I still don't [understand it], but don't waste too much time explaining if you don't want to, just go ahead. [and make the pull request]

 Also, in the interest of disclosure, I'm interested in improving similar parts in SLY, my fork of SLIME.

**Comment by mrkkrp** [comment]
Closing this. Sorry, I didn't get to dig into this and unlikely will because I mostly have lost my interest in Common Lisp.
